hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
spring:
  application:
    name: api-gateway

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

