spring:
  application:
    name: discovery-service
eureka:
  instance:
    hostname: discovery.firstservice.svc
    nonSecurePortEnabled: true
    nonSecurePort: 80
    homePageUrl: http://${eureka.instance.hostname}/
    statusPageUrl: http://${eureka.instance.hostname}/actuator/info/
    healthCheckUrl: http://${eureka.instance.hostname}/actuator/health/
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
