spring:
  application:
    name: first-service
server:
  port: 8086

eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://springsteeltoe.gateway.svc:8761/eureka/
