spring:
  application:
    name: first-service
server:
  port: 8086

eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://spring-cloud-gateway.discovery.svc:8761/eureka/
