spring:
  application:
    name: first-service
eureka:
  instance:
    nonSecurePortEnabled: true
    nonSecurePort: 80
    preferIpAddress: true
    homePageUrl: http://${eureka.instance.hostname}/
  client:
    service-url:
      defaultZone: http://discovery.firstservice.svc/eureka/
