spring:
  application:
    name: first-service
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

