spring:
  application:
    name: second-service
server:
  port: 8087

eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://spring-cloud-gateway.discovery.svc:8761
