spring:
  application:
    name: second-service
server:
  port: 8087

eureka:
  instance:
    preferIpAddress: false
  client:
    service-url:
      defaultZone: http://discovery.firstservice.svc:8761/eureka
